#!/usr/bin/env node
/**
 * build-gallery.js
 *
 * Writes gallery data to gallery-data.js (a separate file, NOT injected
 * into index.html). This avoids the Cloudflare asset-upload caching bug
 * where modifying index.html in-place during the build sometimes gets
 * skipped by the "already uploaded, 0 files changed" optimization.
 *
 * index.html loads this file once via a normal <script src> tag, so it
 * always fetches whatever the latest build wrote, with no in-place
 * HTML mutation involved.
 */

const fs   = require('fs');
const path = require('path');

const GALLERY_DIR = path.join(__dirname, '_gallery');
const OUTPUT_FILE = path.join(__dirname, 'gallery-data.js');

function parseFrontMatter(rawContent) {
  const content = rawContent.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return {};
  const yaml = match[1];
  const result = {};
  yaml.split('\n').forEach(line => {
    const colonIdx = line.indexOf(':');
    if (colonIdx === -1) return;
    const key = line.slice(0, colonIdx).trim();
    let val = line.slice(colonIdx + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) ||
        (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    if (val === 'true')  val = true;
    if (val === 'false') val = false;
    result[key] = val;
  });
  return result;
}

const HARDCODED = [
  { type: 'photo', photo: 'isr-1.jpeg',  title: 'ISR lesson', published: true },
  { type: 'photo', photo: 'isr-2.jpeg',  title: 'ISR lesson', published: true },
  { type: 'photo', photo: 'isr-3.jpeg',  title: 'ISR lesson', published: true },
  { type: 'photo', photo: 'isr-4.jpeg',  title: 'ISR lesson', published: true },
  { type: 'photo', photo: 'isr-5.jpeg',  title: 'ISR lesson', published: true },
  { type: 'photo', photo: 'isr-6.jpeg',  title: 'ISR lesson', published: true },
  { type: 'photo', photo: 'isr-7.png',   title: 'ISR lesson', published: true },
  { type: 'photo', photo: 'isr-8.png',   title: 'ISR lesson', published: true },
  {
    type: 'photo',
    photo: 'https://raw.githubusercontent.com/caseykeown/swim-for-vinny/main/Daphne-baby-in-water.png',
    title: 'Daphne with a baby in the water',
    published: true
  },
  {
    type: 'video',
    video_url: 'https://www.tiktok.com/@daphnemattingly/video/7643985709199658271',
    title: 'TikTok video',
    published: true
  },
  {
    type: 'video',
    video_url: 'https://www.tiktok.com/@daphnemattingly/video/7639901780742081822',
    title: 'TikTok video',
    published: true
  },
];

let cmsItems = [];
let skipped = [];
if (fs.existsSync(GALLERY_DIR)) {
  const files = fs.readdirSync(GALLERY_DIR).filter(f => f.endsWith('.md'));
  files.sort();
  files.forEach(f => {
    const raw = fs.readFileSync(path.join(GALLERY_DIR, f), 'utf8');
    const parsed = parseFrontMatter(raw);
    const hasContent = parsed.photo || parsed.video_url;
    const isPublished = parsed.published !== false;
    if (hasContent && isPublished) {
      cmsItems.push(parsed);
    } else {
      skipped.push({ file: f, reason: !hasContent ? 'no photo/video_url parsed' : 'published=false' });
    }
  });
}

const allItems = [...HARDCODED, ...cmsItems];

// Write a STANDALONE js file. Including a build timestamp comment at the
// top guarantees the file's content (and therefore its hash) changes on
// every single build, even if the gallery items are identical to last
// time — this defeats any "no changes, skip upload" optimization.
const buildTime = new Date().toISOString();
const fileContent =
`// Auto-generated by build-gallery.js — DO NOT EDIT
// Build time: ${buildTime}
window.__GALLERY_DATA__ = ${JSON.stringify(allItems)};
`;

fs.writeFileSync(OUTPUT_FILE, fileContent);
console.log(`Wrote gallery-data.js: ${allItems.length} items (${cmsItems.length} from CMS), build time ${buildTime}`);
if (skipped.length) {
  console.log(`WARNING: ${skipped.length} _gallery file(s) skipped:`);
  skipped.forEach(s => console.log(`  - ${s.file}: ${s.reason}`));
}
